language: android
android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-24
  licenses:
    - '.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace
